module Analysis

using JSON3
using ..TreesSurfaces

export signal_summary, generate_signal_artifacts

function signal_summary()
    state = TreesSurfaces.build_state()
    scenarios = Dict(
        "heat_only" => (100.0, 0.0),
        "balanced" => (60.0, 40.0),
        "proximity_only" => (0.0, 100.0),
    )
    screens = Dict(name => TreesSurfaces.ranked_sites(state["sites"], weights[1], weights[2]) for (name, weights) in scenarios)
    balanced_ids = Set(site["id"] for site in screens["balanced"]["sites"][1:10])
    scenario_summary = Dict{String, Any}()
    for (name, screen) in screens
        top = screen["sites"][1:10]
        scenario_summary[name] = Dict{String, Any}(
            "heat_weight" => screen["heatWeight"],
            "proximity_weight" => screen["proximityWeight"],
            "top_10_ids" => [site["id"] for site in top],
            "top_signal" => first(top)["signal"],
            "top_10_overlap_with_balanced" => length(intersect(Set(site["id"] for site in top), balanced_ids)),
        )
    end
    return Dict{String, Any}(
        "record_count" => length(state["sites"]),
        "scenarios" => scenario_summary,
        "data_completeness" => state["quality"],
    )
end

function csv_escape(value)
    value === nothing && return ""
    string_value = string(value)
    (occursin(',', string_value) || occursin('"', string_value) || occursin('\n', string_value) || occursin('\r', string_value)) || return string_value
    return "\"" * replace(string_value, "\"" => "\"\"") * "\""
end

function analysis_rows(data_dir=TreesSurfaces.DATA_DIR)
    managed_payload = TreesSurfaces.read_json_path(joinpath(data_dir, "brussels-trees-sample.json"))
    heat_payload = TreesSurfaces.read_json_path(joinpath(data_dir, "brussels-tree-heat-sample.json"))
    joined_payload = TreesSurfaces.read_json_path(joinpath(data_dir, "brussels-tree-bike-nearest.json"))
    heat_by_id = Dict(TreesSurfaces.text(get(row, "id", "")) => TreesSurfaces.number(get(row, "heat_pixel", 0)) for row in TreesSurfaces.records(heat_payload))
    points = Any[]
    for row in TreesSurfaces.records(joined_payload)
        id = TreesSurfaces.text(get(row, "id", ""))
        haskey(heat_by_id, id) || continue
        push!(points, Dict{String, Any}(
            "id" => id,
            "street" => get(row, "street", nothing),
            "district" => get(row, "district", nothing) === nothing ? "Unknown" : get(row, "district", "Unknown"),
            "heatPixel" => heat_by_id[id],
            "distanceM" => TreesSurfaces.number(get(row, "nearest_counter_distance_m", 0)),
            "counter" => TreesSurfaces.text(get(row, "nearest_counter", "")),
        ))
    end
    heat_values = [point["heatPixel"] for point in points]
    distances = [point["distanceM"] for point in points]
    min_heat, max_heat = extrema(heat_values)
    min_distance, max_distance = extrema(distances)
    for point in points
        point["heatScore"] = round(max_heat == min_heat ? 50.0 : (point["heatPixel"] - min_heat) / (max_heat - min_heat) * 100; digits = 3)
        point["proximityScore"] = round(100 - (max_distance == min_distance ? 50.0 : (point["distanceM"] - min_distance) / (max_distance - min_distance) * 100); digits = 3)
    end
    return points, managed_payload, heat_payload, min_heat, max_heat, min_distance, max_distance
end

function artifact_row(site)
    Dict{String, Any}(
        "id" => site["id"],
        "street" => site["street"],
        "district" => site["district"],
        "heat_pixel" => site["heatPixel"],
        "nearest_counter" => site["counter"],
        "distance_m" => site["distanceM"],
        "heat_score" => site["heatScore"],
        "proximity_score" => site["proximityScore"],
        "signal" => round(site["signal"]; digits = 3),
    )
end

function markdown_value(value)
    value === nothing && return "Unnamed street"
    replace(string(value), "|" => "\\|")
end

function write_analysis_report(report, output_dir)
    balanced = report["balanced_screening"]
    sensitivity = report["weight_sensitivity"]
    quality = report["data_completeness"]
    lines = [
        "# Tree signal descriptive analysis",
        "",
        "This report was generated by the Julia analytical pipeline from the committed feasibility snapshots.",
        "",
        "> Which observed tree areas combine relatively high heat-stress values with proximity to bicycle counters, and therefore merit more detailed field or mobility analysis?",
        "",
        "## Sample summary",
        "",
        "- Records analyzed: $(report["record_count"]) of $(quality["managed_records"]) managed-tree records.",
        "- WBGT indicator range: $(report["heat_range"][1])–$(report["heat_range"][2]) (source-normalized values, not degrees Celsius).",
        "- Counter distance range: $(report["distance_range_m"][1])–$(report["distance_range_m"][2]) m.",
        "",
        "## Data completeness",
        "",
        "| Stage | Expected | Available | |",
        "|---|---:|---:|---|",
        "| Managed records | $(quality["managed_records"]) | $(quality["managed_records"]) | |",
        "| Heat join | $(quality["managed_records"]) | $(quality["heat_joined_records"]) | |",
        "| Analyzed records | $(quality["managed_records"]) | $(quality["analyzed_records"]) | |",
        "",
        "## Weight sensitivity",
        "",
        "| Scenario | Top-ten overlap with balanced |",
        "|---|---:|",
        "| Heat only | $(sensitivity["heat_only_top_10_overlap"])/10 |",
        "| Proximity only | $(sensitivity["proximity_only_top_10_overlap"])/10 |",
        "",
        "The ranking is exploratory and sample-relative. Counter proximity is a spatial context proxy, not a mobility measure.",
        "",
        "## Balanced screen",
        "",
        "| Rank | ID | Street | Heat | Counter distance | Signal |",
        "|---:|---|---|---:|---:|---:|",
    ]
    for (rank, row) in enumerate(balanced[1:10])
        push!(lines, "| $(rank) | $(row["id"]) | $(markdown_value(row["street"])) | $(row["heat_pixel"]) | $(row["distance_m"]) m | $(row["signal"]) |")
    end
    push!(lines, "")
    push!(lines, "## Interpretation boundary")
    push!(lines, "")
    push!(lines, "- The heat layer represents one representative hot day in 2016.")
    push!(lines, "- Counter distance is not bicycle flow, pedestrian use, or street occupancy.")
    push!(lines, "- These points are candidates for follow-up analysis, not planting recommendations or causal findings.")
    open(joinpath(output_dir, "tree-signal-analysis.md"), "w") do io
        write(io, join(lines, "\n"))
        write(io, "\n")
    end
end

function generate_signal_artifacts(output_dir; data_dir=TreesSurfaces.DATA_DIR)
    mkpath(output_dir)
    points, managed_payload, heat_payload, min_heat, max_heat, min_distance, max_distance = analysis_rows(data_dir)
    scenarios = Dict(
        "heat_only" => (100.0, 0.0),
        "balanced" => (60.0, 40.0),
        "proximity_only" => (0.0, 100.0),
    )
    screens = Dict(name => TreesSurfaces.ranked_sites(points, weights[1], weights[2]) for (name, weights) in scenarios)
    balanced_ids = Set(site["id"] for site in screens["balanced"]["sites"][1:10])
    scenario_rows = Any[]
    for name in ("heat_only", "balanced", "proximity_only")
        screen = screens[name]
        rows = [artifact_row(site) for site in screen["sites"]]
        push!(scenario_rows, Dict{String, Any}(
            "name" => name,
            "weights" => Dict("heat" => screen["heatWeight"], "proximity" => screen["proximityWeight"]),
            "top_10_overlap_with_balanced" => length(intersect(Set(row["id"] for row in rows[1:10]), balanced_ids)),
            "top_records" => rows[1:10],
        ))
    end
    joined_ids = Set(point["id"] for point in points)
    managed_records = TreesSurfaces.records(managed_payload)
    managed_ids = [TreesSurfaces.text(get(row, "id", "")) for row in managed_records]
    heat_records = TreesSurfaces.records(heat_payload)
    heat_ids = Set(TreesSurfaces.text(get(row, "id", "")) for row in heat_records)
    valid_coordinate_ids = Set(
        TreesSurfaces.text(get(row, "id", ""))
        for row in managed_records
        if get(row, "latitude", nothing) isa Number && get(row, "longitude", nothing) isa Number && isfinite(Float64(get(row, "latitude", 0))) && isfinite(Float64(get(row, "longitude", 0)))
    )
    flow_payload = TreesSurfaces.read_json_path(joinpath(data_dir, "brussels-tree-counter-flow.json"))
    flow_records = TreesSurfaces.records(flow_payload)
    flow_record_ids = Set(TreesSurfaces.text(get(row, "id", "")) for row in flow_records)
    measured_flow_records = [row for row in flow_records if get(row, "has_measured_flow", false) == true]
    measured_flow_ids = Set(TreesSurfaces.text(get(row, "id", "")) for row in measured_flow_records)
    missing_coordinate_ids = [id for id in managed_ids if !(id in valid_coordinate_ids)]
    heat_unmatched_ids = [id for id in managed_ids if !(id in heat_ids)]
    mobility_unmatched_ids = [id for id in managed_ids if !(id in joined_ids)]
    analysis_unmatched_ids = [id for id in managed_ids if !(id in joined_ids)]
    flow_context_unmatched_ids = [id for id in managed_ids if !(id in flow_record_ids)]
    measured_flow_unmatched_ids = [id for id in managed_ids if !(id in measured_flow_ids)]
    measured_flow_unmatched_counters = sort(unique(TreesSurfaces.text(get(row, "nearest_counter", "")) for row in flow_records if TreesSurfaces.text(get(row, "id", "")) in measured_flow_unmatched_ids))
    data_completeness = Dict{String, Any}(
        "managed_records" => length(managed_ids),
        "valid_coordinate_records" => length(valid_coordinate_ids),
        "missing_coordinate_ids" => missing_coordinate_ids,
        "heat_joined_records" => length(heat_ids),
        "heat_unmatched_ids" => heat_unmatched_ids,
        "heat_nodata_ids" => [TreesSurfaces.text(get(row, "id", "")) for row in heat_records if TreesSurfaces.number(get(row, "heat_pixel", 0)) == 0],
        "mobility_joined_records" => length(joined_ids),
        "mobility_unmatched_ids" => mobility_unmatched_ids,
        "analyzed_records" => length(joined_ids),
        "analysis_unmatched_ids" => analysis_unmatched_ids,
        "flow_context_joined_records" => length(flow_record_ids),
        "flow_context_unmatched_ids" => flow_context_unmatched_ids,
        "measured_flow_context_records" => length(measured_flow_ids),
        "measured_flow_unmatched_ids" => measured_flow_unmatched_ids,
        "measured_flow_unmatched_counters" => measured_flow_unmatched_counters,
    )
    report = Dict{String, Any}(
        "method" => "min-max normalization within the 100-record feasibility sample",
        "heat_value_semantics" => get(heat_payload, "value_semantics", ""),
        "heat_source_metadata_id" => get(heat_payload, "source_metadata_id", ""),
        "heat_source_licence" => get(heat_payload, "source_licence", ""),
        "record_count" => length(points),
        "heat_range" => [min_heat, max_heat],
        "distance_range_m" => [min_distance, max_distance],
        "balanced_screening" => [artifact_row(site) for site in screens["balanced"]["sites"]],
        "data_completeness" => data_completeness,
        "weight_sensitivity" => Dict(
            "balanced_top_10_ids" => [site["id"] for site in screens["balanced"]["sites"][1:10]],
            "heat_only_top_10_overlap" => scenario_rows[1]["top_10_overlap_with_balanced"],
            "proximity_only_top_10_overlap" => scenario_rows[3]["top_10_overlap_with_balanced"],
            "material_change" => scenario_rows[3]["top_10_overlap_with_balanced"] < 5,
            "interpretation" => "The 60/40 top ten is strongly heat-led; emphasizing proximity materially changes its membership.",
        ),
        "scenarios" => scenario_rows,
        "caveat" => "Rankings are exploratory and depend on sample-relative normalization; proximity is not a mobility measure.",
    )
    open(joinpath(output_dir, "tree-signal-sensitivity.json"), "w") do io
        write(io, JSON3.write(report))
        write(io, "\n")
    end
    fields = ["rank", "id", "street", "district", "heat_pixel", "nearest_counter", "distance_m", "heat_score", "proximity_score", "signal"]
    open(joinpath(output_dir, "tree-signal-balanced-screen.csv"), "w") do io
        println(io, join(fields, ","))
        for (rank, site) in enumerate(screens["balanced"]["sites"])
            row = artifact_row(site)
            values = Any[rank, row["id"], row["street"], row["district"], row["heat_pixel"], row["nearest_counter"], row["distance_m"], row["heat_score"], row["proximity_score"], row["signal"]]
            println(io, join(csv_escape.(values), ","))
        end
    end
    write_analysis_report(report, output_dir)
    return report
end

end
